### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by mbest** [Siddharth11/gradStop.js#1]
This library doesn't work in IE, but it can with a few changes. Since `gradstop.js` is compiled, I don't want to submit a pull request to change it, but I'm not sure how to change the original so that Babel will give the correct output.

Here are the changes I made:

* Use `arguments` instead of the alias `_arguments`.
* Polyfill `Math.trunc`.

**Comment by Siddharth11** [comment]
I appreciate your input @mbest :)
I'll probably separate out all the polyfills in a different file and concat it after compilation.
