### ISSUE TITLE
hsl not correct calculated

### ISSUE THREAD

**Issue by Eisenspalter** [Siddharth11/gradStop.js#2]
if lightness is 100% this `hsl(120, 100%, 100%)` should be white

**Comment by Siddharth11** [comment]
@Eisenspalter can you tell me the exact options object (argument) for which it gave incorrect result.
You can also try this [generator](http://codepen.io/Siddharth11/full/RPvJmO/) I recently made, in my case it's correctly giving white for 100% luminance.

**Comment by Eisenspalter** [comment]
My fault, I haven't seen the white color in the generator example. Shame on me. Nice library

**Comment by Siddharth11** [comment]
Thanks :smile:
